sudo: false

language: python

python:
  - 3.7

install:
  - pip install codecov

script:
  - coverage run tests.py

after_success:
  - codecov --token=b8caad07-f944-4e71-8577-978f7881efe6
  - bash < (curl -s https://codecov.io/bash)

codecov:
 notify:
 require_ci_to_pass: yes
coverage:
 precision: 2
 round: down
 range: “70…100”
status:
 project: yes
 patch: yes
 changes: no
comment:
 layout: “reach, diff, flags, files, footer”
 behavior: default
 require_changes: no
